weights: ./work_dir/recognition/ntu-xsub/random_subject_split/epoch80_model.pt

feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/random_val_data.npy
  label_path: ./data/NTU-RGB-D/xsub/random_val_label.pkl

model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

phase: test
device: 0
test_batch_size: 64
