work_dir: ./work_dir/ntu120-xsubview

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU120-RGB-D/xsubview/train_data.npy
  label_path: ./data/NTU120-RGB-D/xsubview/train_label.pkl
test_feeder_args:
  data_path: ./data/NTU120-RGB-D/xsubview/val_data.npy
  label_path: ./data/NTU120-RGB-D/xsubview/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# optim
weight_decay: 0.0001
base_lr: 0.1
step: [40, 70]

# training
device: [0]
batch_size: 32
test_batch_size: 64
num_epoch: 100